[tool.poetry]
name = "bookstore"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
packages = [{include = "bookstore"}, {include = "api"}]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
django = "^5.0"
djangorestframework = "^3.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
